/*
    This file is part of darktable,
    Copyright (C) 2026 darktable developers.

    darktable is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    darktable is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with darktable.  If not, see <http://www.gnu.org/licenses/>.
*/

#pragma once

#include "common/darktable.h"
#include "common/rasterfile_recipe.h"

#include <glib.h>

G_BEGIN_DECLS

#ifdef HAVE_AI

// headless replay of an AI mask provenance recipe: regenerate the finalised
// mask PNG for `imgid` exactly as the original session produced it -- same
// render at the recorded encode dimensions, same recorded segmentation and
// refinement models pinned to their recorded versions (any mismatch is a
// clean failure), decodes replayed at the recorded boundaries with their
// recorded thresholds, same native-resolution finalisation, and the same
// content-addressed file name derived from the recipe fingerprint. when a
// valid file already exists under that name it is kept as-is (same
// fingerprint = same content) and the call succeeds immediately.
//
// safe to call from a worker job or from a CLI context: the function's own
// code never touches darktable.develop, GTK or dt_control_log (dt_print
// only) -- but its render pipes run every module of the current history,
// which may emit their own traces; the embedded rasterfile instance in
// particular resolves to the very file being regenerated and renders with
// a zeroed mask (silently -- rasterfile.c suppresses the missing-file
// toast when a recipe is present). accepted deviation, documented at the
// implementation: when the current distortion history no longer matches
// the recorded distort_hash the replay proceeds on the CURRENT state, so
// the regenerated bytes can then differ from the original under the same
// fingerprint -- confined to the guide render, ONNX-variance class.
//
// contract for the caller:
//  - at most ONE call in flight per fingerprint (A4's anti-respawn table
//    guarantees it); concurrent calls on the same fingerprint would race
//    on the temp files and waste the whole compute;
//  - never call from a pixelpipe thread: a replay costs tens of seconds
//    (two full-resolution renders plus inferences);
//  - the call may run alongside an interactive session at the price of
//    additional ORT sessions in VRAM; its native pass is serialised
//    against the interactive finalisation job and fails cleanly (retry
//    later) when one is running; the shared per-image .seg cache is only
//    written when absent, never overwritten.
//
// `keep_going` (nullable) is polled between the expensive steps; return
// FALSE from it to abort. returns TRUE when the file exists on return.
//
// the implementation lives in object.c, next to the interactive session
// code it shares its compute path with.
gboolean dt_object_recipe_compute(const dt_rf_recipe_t *recipe,
                                  const dt_imgid_t imgid,
                                  gboolean (*keep_going)(void *),
                                  void *user);

// schedule a background recompute of a recipe's mask file, guarded by an
// anti-respawn table (one recompute in flight per recipe+image; a failure
// is not retried within the session). safe to call from a pixelpipe thread:
// it only marks the table and enqueues a job. when the job system is down
// (darktable-cli) the job runs INLINE inside this call; the return value is
// TRUE exactly in that case, meaning the file may exist right now and one
// immediate retry of the read is worth it. GUI callers always get FALSE and
// are notified by a pipe reprocess when the recompute lands.
gboolean dt_object_recipe_schedule_recompute(const dt_rf_recipe_t *recipe,
                                             const dt_imgid_t imgid);

#else

// without AI support a recipe can never be recomputed on this machine; the
// inline stub keeps future call sites free of conditional compilation
static inline gboolean dt_object_recipe_compute(const dt_rf_recipe_t *recipe,
                                                const dt_imgid_t imgid,
                                                gboolean (*keep_going)(void *),
                                                void *user)
{
  (void)recipe;
  (void)imgid;
  (void)keep_going;
  (void)user;
  return FALSE;
}

static inline gboolean
dt_object_recipe_schedule_recompute(const dt_rf_recipe_t *recipe,
                                    const dt_imgid_t imgid)
{
  (void)recipe;
  (void)imgid;
  return FALSE;
}

#endif // HAVE_AI

G_END_DECLS

// clang-format off
// modelines: These editor modelines have been set for all relevant files by tools/update_modelines.py
// vim: shiftwidth=2 expandtab tabstop=2 cindent
// kate: tab-indents: off; indent-width 2; replace-tabs on; indent-mode cstyle; remove-trailing-spaces modified;
// clang-format on
